services:
  - type: web
    name: interview-platform
    env: docker
    plan: free
    rootDir: cohorts/2025/02-end-to-end/interview-platform
    dockerContext: .
    dockerfilePath: Dockerfile
    numInstances: 1
    envVars:
      - key: PORT
        value: 10000
